// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/gmarcha/notion-goswagger-api/internal/v1/goswagger/models"
)

// CampusCreateCreatedCode is the HTTP code returned for type CampusCreateCreated
const CampusCreateCreatedCode int = 201

/*
CampusCreateCreated Created

swagger:response campusCreateCreated
*/
type CampusCreateCreated struct {

	/*
	  In: Body
	*/
	Payload []*models.Task `json:"body,omitempty"`
}

// NewCampusCreateCreated creates CampusCreateCreated with default headers values
func NewCampusCreateCreated() *CampusCreateCreated {

	return &CampusCreateCreated{}
}

// WithPayload adds the payload to the campus create created response
func (o *CampusCreateCreated) WithPayload(payload []*models.Task) *CampusCreateCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the campus create created response
func (o *CampusCreateCreated) SetPayload(payload []*models.Task) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CampusCreateCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Task, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// CampusCreateInternalServerErrorCode is the HTTP code returned for type CampusCreateInternalServerError
const CampusCreateInternalServerErrorCode int = 500

/*
CampusCreateInternalServerError Internal Server Error

swagger:response campusCreateInternalServerError
*/
type CampusCreateInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCampusCreateInternalServerError creates CampusCreateInternalServerError with default headers values
func NewCampusCreateInternalServerError() *CampusCreateInternalServerError {

	return &CampusCreateInternalServerError{}
}

// WithPayload adds the payload to the campus create internal server error response
func (o *CampusCreateInternalServerError) WithPayload(payload *models.Error) *CampusCreateInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the campus create internal server error response
func (o *CampusCreateInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CampusCreateInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
