// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PoolCreateHandlerFunc turns a function with the right signature into a pool create handler
type PoolCreateHandlerFunc func(PoolCreateParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PoolCreateHandlerFunc) Handle(params PoolCreateParams) middleware.Responder {
	return fn(params)
}

// PoolCreateHandler interface for that can handle valid pool create params
type PoolCreateHandler interface {
	Handle(PoolCreateParams) middleware.Responder
}

// NewPoolCreate creates a new http.Handler for the pool create operation
func NewPoolCreate(ctx *middleware.Context, handler PoolCreateHandler) *PoolCreate {
	return &PoolCreate{Context: ctx, Handler: handler}
}

/*
	PoolCreate swagger:route POST /tasks/pools/{id} Task poolCreate

# Create pool tasks

Create a task list linked to pool setup.
*/
type PoolCreate struct {
	Context *middleware.Context
	Handler PoolCreateHandler
}

func (o *PoolCreate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPoolCreateParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
