version: "3.9"

services:
  n8n:
    image: n8nio/n8n
    entrypoint: n8n start --tunnel
    ports:
      - 8080:5678
    volumes:
      - ~/.n8n:/home/node/.n8n
    restart: "unless-stopped"
  # client:
  #   build:
  #     context: ../notion-trigger
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ../notion-trigger:/build
  #   env_file:
  #     - .env
  #   restart: "unless-stopped"
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8081:3001
    volumes:
      - ./:/build
    env_file:
      - .env
    restart: "unless-stopped"