FROM golang:alpine as build

WORKDIR /build
COPY . .

CMD [ "go", "build", "-o", "bin/v1/main.out", "cmd/v1/main.go" ]

FROM alpine

WORKDIR /usr/local/bin
COPY --from=build /build/bin/v1/main.out .

CMD [ "./main.out", "--host", "0.0.0.0", "--port", "80" ]
