swagger: "2.0"

info:
  title: Notion API
  description: An API to automate content creation on Notion.
  contact: {}
  version: "0.1"

host: api:3001
basePath: /v1
schemes:
  - http

consumes:
  - application/json
produces:
  - application/json

paths:
  /campus/sync:
    get:
      summary: Synchronize campus page
      description: Synchronize shared campus page with internal databases.
      tags:
        - Campus
      operationId: sync
      responses:
        "204":
          description: No content
        "500":
          $ref: '#/responses/500'

  /issues:
    post:
      summary: Create issue
      description: Create an issue from Jira.
      tags:
        - Issue
      operationId: create
      parameters:
        - in: body
          name: issue
          required: true
          description: Issue content.
          schema:
            $ref: '#/definitions/Issue'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/Issue'
        "500":
          $ref: '#/responses/500'
  /issues/{id}:
    parameters:
      - in: path
        name: id
        required: true
        description: Issue ID from Jira.
        type: string
    put:
      summary: Update issue
      description: Update an issue from Jira.
      tags:
        - Issue
      operationId: update
      parameters:
        - in: body
          name: issue
          required: true
          description: Issue content.
          schema:
            $ref: '#/definitions/Issue'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Issue'
        "500":
          $ref: '#/responses/500'
    delete:
      summary: Delete issue
      description: Delete an issue from Jira.
      tags:
        - Issue
      operationId: delete
      responses:
        "204":
          description: No Content
        "500":
          $ref: '#/responses/500'

responses:
  400:
    description: Bad request
    schema:
      $ref: '#/definitions/Error'
  500:
    description: Internal Server Error
    schema:
      $ref: '#/definitions/Error'

definitions:
  Issue:
    type: object
    properties:
      name:
        type: string
      status:
        type: string
      type:
        type: string
      jiraIssueID:
        type: string
  Error:
    type: object
    properties:
      code:
        type: integer
        example: 500
      message:
        type: string
        example: Error message
