// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Notion API
//
//	An API to automate content creation on Notion.
//	Schemes:
//	  http
//	Host: api:3001
//	BasePath: /v1
//	Version: 0.1
//	Contact:
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
